### ISSUE TITLE
x86 version can not run on win8(x64),  and x64 version report missing msvcr120.dll

### ISSUE THREAD

**Issue by freboat** [mayswind/PuTTY-ng#2]
i test the putty-ng_x86.zip,  it can not run on win8(x64):  report "应用程序无法正常启动(0xc000007b). 请点击确定关闭应用程序“

试了老版的putty-nd 6.6, 6.4的二进制包都有这个问题

64位的包，报缺少msvcr120.dll， 下载放在相同目录能正常用

**Comment by mayswind** [comment]
项目是vc++ 2013编译的，需要安装vc++ 2013的可再发行包。参考这个 https://support.microsoft.com/zh-cn/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package
