### ISSUE TITLE
自动唤出其他软件的窗口

### ISSUE THREAD

**Issue by korimas** [mayswind/PuTTY-ng#3]
提个bug:
我是双屏工作，在创建新的连接时，会自动把我的另一个屏幕上显示我的企业微信软件。

**Comment by mayswind** [comment]
“会自动把我的另一个屏幕上显示我的企业微信软件” 这句是啥意思？

**Comment by korimas** [comment]
我有两个显示器，显示器A打开了putty-ng，显示器B比如打开了浏览器，然后putty-ng连接新的主机的时候，显示器B会自动打开我的企业微信到最前面，即使我之前已经把企业微信的窗口关了（没退出）

**Comment by zpdev** [comment]
这软件很赞，希望能持续更新~

**Comment by korimas** [comment]
发现把设置页面关掉的时候，也会触发这个问题。

**Comment by korimas** [comment]
好像就影响企业微信，在同一个显示器里也一样的问题，感觉是不是什么全局钩子引起的

**Comment by korimas** [comment]
找到问题了，Alt + Shift + S，应该是自动触发了这个~，这个快捷键正好是显示企业微信窗口的

**Comment by mayswind** [comment]
快捷键可以自己改...

**Comment by korimas** [comment]
问题是，我没有按快捷键，是在关掉配置窗口的时候，自动触发了这个快捷功能。

**Comment by mayswind** [comment]
你截一个Global Settings里Global Shortcuts里的截图？

**Comment by korimas** [comment]
截图奉上，请查看。
![image](https://user-images.githubusercontent.com/15672287/71539977-2e254000-297f-11ea-8937-ab9b2c970d3c.png)

**Comment by mayswind** [comment]
PuTTY-ng唯一有定义快捷键的地方就是这里了，而且我用其他软件注册全局关键键后也无法复现...看上去跟快捷键无关，感觉还是得从企业微信那入手

**Comment by korimas** [comment]
的确感觉只有企业微信有影响。

**Comment by korimas** [comment]
问题复现，把企业微信的红框里的快捷键取消掉就没问题了。
![image](https://user-images.githubusercontent.com/15672287/81141980-d3d96300-8fa0-11ea-82e3-ab42ed47d063.png)
试了一下，的确触发了企业微信里的搜索，搜索框被自动激活。

**Comment by mayswind** [comment]
这里默认配置的是啥？

**Comment by korimas** [comment]
> 这里默认配置的是啥？

截图里就是企业微信默认的快捷键

**Comment by mayswind** [comment]
Alt+Alt是啥意思...

**Comment by zpdev** [comment]
就是连续按两次alt键

**Comment by korimas** [comment]
> Alt+Alt是啥意思...

就是连续按两次alt键

**Comment by mayswind** [comment]
@zpdev 你试试这个还会出问题么？
[putty-ng.zip](https://github.com/mayswind/PuTTY-ng/files/4594272/putty-ng.zip)

**Comment by korimas** [comment]
> @zpdev 你试试这个还会出问题么？
> [putty-ng.zip](https://github.com/mayswind/PuTTY-ng/files/4594272/putty-ng.zip)

这个没有讨论的问题了，但是貌似保存的用户名密码没效果了，每次登陆都要输入用户名和密码

**Comment by mayswind** [comment]
@zpdev 是的，这是个临时的版本只是确认一下你的问题，等下一个版本彻底修复这个问题吧

**Comment by korimas** [comment]
> @zpdev 是的，这是个临时的版本只是确认一下你的问题，等下一个版本彻底修复这个问题吧

OK，多谢
