### ISSUE TITLE
VC2019编译无法通过

### ISSUE THREAD

**Issue by hongnod** [mayswind/PuTTY-ng#4]
尝试用VC2019编译，一堆报错。搞定了一些，最后在view和ui_base上搞不定。

**Comment by hongnod** [comment]
还有libevent

**Comment by mayswind** [comment]
用VS2013安装v12.0版本的MSVC和Win32SDK，然后平台工具集选 “Visual Studio 2013 - Windows XP (v120_xp)”。或者直接用VS2013。

**Comment by hongnod** [comment]
经过一番折腾，VC2019构建成功。不过要兼容VC2013需要做额外的ifdef。VC2019构建版：   https://github.com/topillar/PuTTY-ng

**Comment by mayswind** [comment]
恭喜你
